### ISSUE TITLE
Definición y distribución de colores

### ISSUE THREAD

**Issue by aguja2013** [estebanrfp/myp-terminal#12]
Ya con la estructura definida probamos y aplicamos los colores definitivos

**Comment by slvr** [comment]
Que tal estas ?

A. http://paletton.com/palette.php?uid=13i0u0kllll000A5%2B00J3%2B%2ByA%2B%2B

B. http://paletton.com/palette.php?uid=12r0u0kllll%2B%2B20w0bGaGu%2B00UZ

C. http://paletton.com/palette.php?uid=13L0u0kllll%2B%2B20w0bGaGu%2B00UZ

D. http://paletton.com/palette.php?uid=12G0u0kllll004X1R00Vt%2B%2BHU%2B%2B

E. http://paletton.com/palette.php?uid=13s0u0kuL%2B%2BRmjJRmjJ5sWq5sWq

**Comment by aguja2013** [comment]
he puesto los colores de la primera paleta sugerida por @slvr cf202fca21bfb6fe32cabf7bc2700558ce8a0f8c . Si les parece bien vamos cerrando este issue
