### ISSUE TITLE
Definir gráfico del monitor

### ISSUE THREAD

**Issue by aguja2013** [estebanrfp/myp-terminal#2]
Definir tipo de archivo de imágen ,  estilo, tamaño y color  del monitor.

**Comment by aguja2013** [comment]
me parecen muy buenas. Tomando estas referencias imaginé algo así:
![monitor](https://cloud.githubusercontent.com/assets/9625917/6587000/a4a1301a-c75d-11e4-8a6b-24dd3962f093.png). Podríamos poner la base con un svg y le damos alguna animación con css3.

**Comment by slvr** [comment]
Tambien me gusta asi ! y tambien lo otro, con el svg y css Perfecto :+1:

**Comment by aguja2013** [comment]
bien! me voy a poner a experimentarlo en una rama, me asigno el issue, cualquier idea de mejora me avisan. saludos!

**Comment by estebanrfp** [comment]
Ya esta hecho, el cambio

**Comment by estebanrfp** [comment]
Espera, estamos respondiendonos sin saber sobre que tema, intentemos tener una conversación, estoy reunido con antonio, please, conéctate si puedes un min

**Comment by slvr** [comment]
lograste definir ?

**Comment by aguja2013** [comment]
Definido
