### ISSUE TITLE
Definir tipografía

### ISSUE THREAD

**Issue by aguja2013** [estebanrfp/myp-terminal#3]

**Comment by slvr** [comment]
Bueno la ultima que agregaste podría ser , se llama DIGITALDREAM si no estoy mal , si les parece bien esa podríamos dejarla , comenten :)

**Comment by aguja2013** [comment]
Si, efectivamente es DIGITALDREAM, se suman a esta tipografía CONSOLAS y 'Wallpoet'. Cómo lo ven?

**Comment by slvr** [comment]
Perfecto :)
