### ISSUE TITLE
Definir el listado de comandos que conformarán el perfil de un usuario

### ISSUE THREAD

**Issue by estebanrfp** [estebanrfp/myp-terminal#5]
Tendremos que hacer el listado de comandos para yo poder trabajar en la ejecución de funciones.

**Comment by aguja2013** [comment]
descripción
tecnologías
trabajos
proyectos
contacto...

que les parece si los comandos en sí sean mas compactos para que el usuario escriba menos, el help quedaría algo así:
                  Comandos disponibles:
acción                    escriba

limpiar                   clear
info                        i
estudios                es
habilidades           hab
trabajos                tr
proyectos             py
contacto               cnt    
(Hasta lo podríamos hacer de un sólo caracter, número, etc)

**Comment by estebanrfp** [comment]
Hemos cotejado con Antonio, y en primera instancia, lo dejamos con la estructura que sugeriste,
ya he hecho la modificación en el commit b5e7de3,  has pull
